name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
          run_install: true
      - run: pnpm test
