name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nodejs: [12, 14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
          run_install: true
      - run: pnpm test
